graph BT
  class_analyzechainscommand["AnalyzeChainsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_analyzecommand["AnalyzeCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_analyzeiocommand["AnalyzeIOCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_buildcommand["BuildCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_checklinkscommand["CheckLinksCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_commandregistry["CommandRegistry"] -.->|extends| class_basecommand["BaseCommand"]
  class_helpcommand["HelpCommand"] -.->|extends| class_commandregistry["CommandRegistry"]
  class_healthcommand["HealthCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_helpcommand["HelpCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_indexdocscommand["IndexDocsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_parallelworkcommand["ParallelWorkCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_parsecommand["ParseCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_idcommand["IdCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_improvecommand["ImproveCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_installhookcommand["InstallHookCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_uninstallhookcommand["UninstallHookCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_suggestcommand["SuggestCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_initcommand["InitCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_idnewcommand["IdNewCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_validatespeccommand["ValidateSpecCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_generatedocscommand["GenerateDocsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  interface_registryentrynode["RegistryEntryNode"] -.->|extends| class_basecommand["BaseCommand"]
  class_depscommand["DepsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_usedbycommand["UsedByCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_whousescommand["WhoUsesCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_orphanscommand["OrphansCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_undocumentedcommand["UndocumentedCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_treecommand["TreeCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_checkduplicatescommand["CheckDuplicatesCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_specstatuscommand["SpecStatusCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_findunuseddocscommand["FindUnusedDocsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_spechistorycommand["SpecHistoryCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_specdiffcommand["SpecDiffCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_specbumpcommand["SpecBumpCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_finddoccommand["FindDocCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_planscommand["PlansCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_findmethodcommand["FindMethodCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_todoscommand["TodosCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_statscommand["StatsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_coreapicommand["CoreApiCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_scancommand["ScanCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_synccoveragecommand["SyncCoverageCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_untestedcommand["UntestedCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_withoutresponsibilitycommand["WithoutResponsibilityCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_withoutcontractcommand["WithoutContractCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_fixcommand["FixCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_testrelationshipscommand["TestRelationshipsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_typechaincommand["TypeChainCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_findroottypescommand["FindRootTypesCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_detectcirculartypescommand["DetectCircularTypesCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_updatebacklinkscommand["UpdateBacklinksCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_updatesymbolrefscommand["UpdateSymbolRefsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_usagecommand["UsageCommand"] -.->|extends| class_basecommand["BaseCommand"]
  interface_relationshiprow["RelationshipRow"] -.->|extends| class_basecommand["BaseCommand"]
  class_validatecommand["ValidateCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_validatedocscommand["ValidateDocsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  class_visualizedepscommand["VisualizeDepsCommand"] -.->|extends| class_basecommand["BaseCommand"]
  interface_symbolrow["SymbolRow"] -.->|extends| class_basecommand["BaseCommand"]