graph TD
  src_index_ts["index.ts"] --> src_generator_MarkdownGenerator_ts["MarkdownGenerator.ts"]
  src_index_ts["index.ts"] --> src_parser_TSDocParser_ts["TSDocParser.ts"]
  src_index_ts["index.ts"] --> src_validator_ConventionValidator_ts["ConventionValidator.ts"]
  src_index_ts["index.ts"] --> src_analyzer_CodeHealthChecker_ts["CodeHealthChecker.ts"]
  src_index_ts["index.ts"] --> src_analyzer_CoverageParser_ts["CoverageParser.ts"]
  src_index_ts["index.ts"] --> src_analyzer_CoverageSyncAdapter_ts["CoverageSyncAdapter.ts"]
  src_index_ts["index.ts"] --> src_analyzer_IstanbulCoverageAdapter_ts["IstanbulCoverageAdapter.ts"]
  src_index_ts["index.ts"] --> src_analyzer_MissingLinkDetector_ts["MissingLinkDetector.ts"]
  src_index_ts["index.ts"] --> src_analyzer_PreCommitChecker_ts["PreCommitChecker.ts"]
  src_index_ts["index.ts"] --> src_analyzer_DocumentationAnalyzer_ts["DocumentationAnalyzer.ts"]
  src_index_ts["index.ts"] --> src_analyzer_DomainStructureAnalyzer_ts["DomainStructureAnalyzer.ts"]
  src_index_ts["index.ts"] --> src_analyzer_ImportanceClassifier_ts["ImportanceClassifier.ts"]
  src_index_ts["index.ts"] --> src_analyzer_InterfaceAnalyzer_ts["InterfaceAnalyzer.ts"]
  src_index_ts["index.ts"] --> src_analyzer_InterfaceDependencyMapper_ts["InterfaceDependencyMapper.ts"]
  src_index_ts["index.ts"] --> src_analyzer_StatsComparator_ts["StatsComparator.ts"]
  src_index_ts["index.ts"] --> src_analyzer_StatsHistoryManager_ts["StatsHistoryManager.ts"]
  src_index_ts["index.ts"] --> src_analyzer_TestCoverageAnalyzer_ts["TestCoverageAnalyzer.ts"]
  src_index_ts["index.ts"] --> src_analyzer_TrackableStatsCollector_ts["TrackableStatsCollector.ts"]
  src_index_ts["index.ts"] --> src_analyzer_TypeChainTracer_ts["TypeChainTracer.ts"]
  src_index_ts["index.ts"] --> src_analyzer_CallGraphAnalyzer_ts["CallGraphAnalyzer.ts"]
  src_index_ts["index.ts"] --> src_analyzer_DependencyChainAnalyzer_ts["DependencyChainAnalyzer.ts"]
  src_index_ts["index.ts"] --> src_analyzer_IODependencyAnalyzer_ts["IODependencyAnalyzer.ts"]
  src_index_ts["index.ts"] --> src_parser_EnhancedDocExtractor_ts["EnhancedDocExtractor.ts"]
  src_index_ts["index.ts"] --> src_config_ConfigManager_ts["ConfigManager.ts"]
  src_index_ts["index.ts"] --> src_fixer_DocumentationFixer_ts["DocumentationFixer.ts"]
  src_index_ts["index.ts"] --> src_fixer_RecursiveImprover_ts["RecursiveImprover.ts"]
  src_index_ts["index.ts"] --> src_fold_CommentExporter_ts["CommentExporter.ts"]
  src_index_ts["index.ts"] --> src_fold_CommentImporter_ts["CommentImporter.ts"]
  src_index_ts["index.ts"] --> src_fold_CommentStateManager_ts["CommentStateManager.ts"]
  src_index_ts["index.ts"] --> src_generator_EnhancedMarkdownGenerator_ts["EnhancedMarkdownGenerator.ts"]
  src_index_ts["index.ts"] --> src_generator_InsightDocGenerator_ts["InsightDocGenerator.ts"]
  src_index_ts["index.ts"] --> src_generator_RelatedDocsGenerator_ts["RelatedDocsGenerator.ts"]
  src_index_ts["index.ts"] --> src_graph_DepthTraverser_ts["DepthTraverser.ts"]
  src_index_ts["index.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_index_ts["index.ts"] --> src_graph_SymbolSearchEngine_ts["SymbolSearchEngine.ts"]
  src_index_ts["index.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_index_ts["index.ts"] --> src_types_core_parse_ts["parse.ts"]
  src_index_ts["index.ts"] --> src_validator_ConnectivityValidator_ts["ConnectivityValidator.ts"]
  src_index_ts["index.ts"] --> src_validator_StrictModeValidator_ts["StrictModeValidator.ts"]
  src_index_ts["index.ts"] --> src_validator_ModuleSpecValidator_ts["ModuleSpecValidator.ts"]
  src_index_ts["index.ts"] --> src_linking_DocCodeLinker_ts["DocCodeLinker.ts"]
  src_index_ts["index.ts"] --> src_linking_LinkValidator_ts["LinkValidator.ts"]
  src_index_ts["index.ts"] --> src_doc_symbol_BacklinkGenerator_ts["BacklinkGenerator.ts"]
  src_index_ts["index.ts"] --> src_doc_symbol_DocumentSymbolParser_ts["DocumentSymbolParser.ts"]
  src_index_ts["index.ts"] --> src_types_feature_doc_symbol_ts["doc-symbol.ts"]
  src_index_ts["index.ts"] --> src_doc_symbol_TSDocSymbolParser_ts["TSDocSymbolParser.ts"]
  src_index_ts["index.ts"] --> src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"]
  src_index_ts["index.ts"] --> src_generator_ModuleSpecMarkdownFormatter_ts["ModuleSpecMarkdownFormatter.ts"]
  src_index_ts["index.ts"] --> src_types_spec_module_spec_ts["module-spec.ts"]
  src_index_ts["index.ts"] --> src_types_tags_enhanced_ts["enhanced.ts"]
  src_cli_ts["cli.ts"] --> src_analytics_UsageTracker_ts["UsageTracker.ts"]
  src_cli_ts["cli.ts"] --> src_commands_AnalyzeCommand_ts["AnalyzeCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_AnalyzeIOCommand_ts["AnalyzeIOCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_BuildCommand_ts["BuildCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_VisualizeDepsCommand_ts["VisualizeDepsCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_Phase6Commands_ts["Phase6Commands.ts"]
  src_cli_ts["cli.ts"] --> src_commands_CheckLinksCommand_ts["CheckLinksCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_CommandRegistry_ts["CommandRegistry.ts"]
  src_cli_ts["cli.ts"] --> src_commands_Phase7Commands_ts["Phase7Commands.ts"]
  src_cli_ts["cli.ts"] --> src_commands_Phase5Commands_ts["Phase5Commands.ts"]
  src_cli_ts["cli.ts"] --> src_commands_Phase8Commands_ts["Phase8Commands.ts"]
  src_cli_ts["cli.ts"] --> src_commands_Phase4Commands_ts["Phase4Commands.ts"]
  src_cli_ts["cli.ts"] --> src_commands_HealthCommand_ts["HealthCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_HelpCommand_ts["HelpCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_Phase10Commands_ts["Phase10Commands.ts"]
  src_cli_ts["cli.ts"] --> src_commands_IndexDocsCommand_ts["IndexDocsCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_ParseCommand_ts["ParseCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_UpdateBacklinksCommand_ts["UpdateBacklinksCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_UpdateSymbolRefsCommand_ts["UpdateSymbolRefsCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_UsageCommand_ts["UsageCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_ValidateCommand_ts["ValidateCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_ValidateDocsCommand_ts["ValidateDocsCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_TypeChainCommand_ts["TypeChainCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_ParallelWorkCommand_ts["ParallelWorkCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_AnalyzeChainsCommand_ts["AnalyzeChainsCommand.ts"]
  src_cli_ts["cli.ts"] --> src_commands_AnalyzeCallsCommand_ts["AnalyzeCallsCommand.ts"]
  src_cli_ts["cli.ts"] --> src_config_ConfigManager_ts["ConfigManager.ts"]
  src_cli_ts["cli.ts"] --> src_types_analytics_index_ts["index.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_storage_SymbolRegistryManager_ts["SymbolRegistryManager.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_graph_SymbolSearchEngine_ts["SymbolSearchEngine.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_types_graph_graph_ts["graph.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_types_tags_base_ts["base.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_types_tags_enhanced_ts["enhanced.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_analyzer_CodeHealthChecker_ts["CodeHealthChecker.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_validator_ConnectivityValidator_ts["ConnectivityValidator.ts"]
  src_storage_DatabaseManager_ts["DatabaseManager.ts"] --> src_config_ConfigManager_ts["ConfigManager.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_analyzer_CodeHealthChecker_ts["CodeHealthChecker.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_config_ConfigManager_ts["ConfigManager.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_storage_SymbolRegistryManager_ts["SymbolRegistryManager.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_spec_SpecCompletenessValidator_ts["SpecCompletenessValidator.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_parser_EnhancedDocExtractor_ts["EnhancedDocExtractor.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_generator_EnhancedMarkdownGenerator_ts["EnhancedMarkdownGenerator.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_types_analysis_quality_ts["quality.ts"]
  src_commands_Phase4Commands_ts["Phase4Commands.ts"] --> src_types_graph_graph_ts["graph.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_storage_SymbolRegistryManager_ts["SymbolRegistryManager.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_types_graph_graph_ts["graph.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_types_tags_base_ts["base.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_types_tags_enhanced_ts["enhanced.ts"]
  src_commands_ValidateCommand_ts["ValidateCommand.ts"] --> src_validator_ConnectivityValidator_ts["ConnectivityValidator.ts"]
  src_commands_Phase6Commands_ts["Phase6Commands.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_Phase6Commands_ts["Phase6Commands.ts"] --> src_spec_SpecContentSimilarityChecker_ts["SpecContentSimilarityChecker.ts"]
  src_commands_Phase6Commands_ts["Phase6Commands.ts"] --> src_spec_SpecStatusManager_ts["SpecStatusManager.ts"]
  src_commands_Phase6Commands_ts["Phase6Commands.ts"] --> src_spec_UnusedDocumentDetector_ts["UnusedDocumentDetector.ts"]
  src_commands_Phase6Commands_ts["Phase6Commands.ts"] --> src_spec_SpecVersionManager_ts["SpecVersionManager.ts"]
  src_commands_Phase6Commands_ts["Phase6Commands.ts"] --> src_doc_symbol_DocumentSymbolParser_ts["DocumentSymbolParser.ts"]
  src_commands_Phase6Commands_ts["Phase6Commands.ts"] --> src_types_feature_doc_symbol_ts["doc-symbol.ts"]
  src_commands_Phase7Commands_ts["Phase7Commands.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_Phase7Commands_ts["Phase7Commands.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_Phase7Commands_ts["Phase7Commands.ts"] --> src_storage_SymbolRegistryManager_ts["SymbolRegistryManager.ts"]
  src_commands_Phase7Commands_ts["Phase7Commands.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_Phase7Commands_ts["Phase7Commands.ts"] --> src_types_graph_graph_ts["graph.ts"]
  src_commands_Phase7Commands_ts["Phase7Commands.ts"] --> src_types_tags_base_ts["base.ts"]
  src_commands_Phase7Commands_ts["Phase7Commands.ts"] --> src_types_tags_enhanced_ts["enhanced.ts"]
  src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"] --> src_config_ConfigManager_ts["ConfigManager.ts"]
  src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"] --> src_analyzer_TestRelationshipExtractor_ts["TestRelationshipExtractor.ts"]
  src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"] --> src_analyzer_IntegrationCoverageCalculator_ts["IntegrationCoverageCalculator.ts"]
  src_commands_TestRelationshipsCommand_ts["TestRelationshipsCommand.ts"] --> src_types_analysis_test_relationships_ts["test-relationships.ts"]
  src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"] --> src_parser_TSDocParser_ts["TSDocParser.ts"]
  src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"] --> src_analyzer_ASTSymbolExtractor_ts["ASTSymbolExtractor.ts"]
  src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"] --> src_parser_EnhancedDocExtractor_ts["EnhancedDocExtractor.ts"]
  src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"] --> src_parser_ModuleSpecTagParser_ts["ModuleSpecTagParser.ts"]
  src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"] --> src_types_tags_module_spec_tags_ts["module-spec-tags.ts"]
  src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"] --> src_types_spec_module_spec_ts["module-spec.ts"]
  src_generator_ModuleSpecGenerator_ts["ModuleSpecGenerator.ts"] --> src_types_tags_enhanced_ts["enhanced.ts"]
  src_commands_Phase5Commands_ts["Phase5Commands.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_Phase5Commands_ts["Phase5Commands.ts"] --> src_storage_SymbolRegistryManager_ts["SymbolRegistryManager.ts"]
  src_commands_Phase5Commands_ts["Phase5Commands.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_Phase5Commands_ts["Phase5Commands.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_Phase5Commands_ts["Phase5Commands.ts"] --> src_graph_SymbolSearchEngine_ts["SymbolSearchEngine.ts"]
  src_commands_Phase5Commands_ts["Phase5Commands.ts"] --> src_types_graph_graph_ts["graph.ts"]
  src_commands_Phase8Commands_ts["Phase8Commands.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_Phase8Commands_ts["Phase8Commands.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_Phase8Commands_ts["Phase8Commands.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_Phase8Commands_ts["Phase8Commands.ts"] --> src_graph_SymbolSearchEngine_ts["SymbolSearchEngine.ts"]
  src_commands_Phase8Commands_ts["Phase8Commands.ts"] --> src_types_graph_graph_ts["graph.ts"]
  src_commands_Phase8Commands_ts["Phase8Commands.ts"] --> src_analyzer_CodeHealthChecker_ts["CodeHealthChecker.ts"]
  src_commands_ParallelWorkCommand_ts["ParallelWorkCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_ParallelWorkCommand_ts["ParallelWorkCommand.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_ParallelWorkCommand_ts["ParallelWorkCommand.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_ParallelWorkCommand_ts["ParallelWorkCommand.ts"] --> src_config_ConfigManager_ts["ConfigManager.ts"]
  src_commands_ParallelWorkCommand_ts["ParallelWorkCommand.ts"] --> src_analyzer_ParallelWorkDetector_ts["ParallelWorkDetector.ts"]
  src_commands_TypeChainCommand_ts["TypeChainCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_TypeChainCommand_ts["TypeChainCommand.ts"] --> src_analyzer_InterfaceAnalyzer_ts["InterfaceAnalyzer.ts"]
  src_commands_TypeChainCommand_ts["TypeChainCommand.ts"] --> src_analyzer_InterfaceDependencyMapper_ts["InterfaceDependencyMapper.ts"]
  src_commands_TypeChainCommand_ts["TypeChainCommand.ts"] --> src_analyzer_TypeChainTracer_ts["TypeChainTracer.ts"]
  src_commands_TypeChainCommand_ts["TypeChainCommand.ts"] --> src_types_domain_type_chain_ts["type-chain.ts"]
  src_commands_UpdateBacklinksCommand_ts["UpdateBacklinksCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_UpdateBacklinksCommand_ts["UpdateBacklinksCommand.ts"] --> src_doc_symbol_DocumentSymbolParser_ts["DocumentSymbolParser.ts"]
  src_commands_UpdateBacklinksCommand_ts["UpdateBacklinksCommand.ts"] --> src_types_feature_doc_symbol_ts["doc-symbol.ts"]
  src_commands_UpdateBacklinksCommand_ts["UpdateBacklinksCommand.ts"] --> src_doc_symbol_TSDocSymbolParser_ts["TSDocSymbolParser.ts"]
  src_commands_UpdateBacklinksCommand_ts["UpdateBacklinksCommand.ts"] --> src_doc_symbol_BacklinkGenerator_ts["BacklinkGenerator.ts"]
  src_commands_UpdateSymbolRefsCommand_ts["UpdateSymbolRefsCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_UpdateSymbolRefsCommand_ts["UpdateSymbolRefsCommand.ts"] --> src_doc_symbol_DocumentSymbolParser_ts["DocumentSymbolParser.ts"]
  src_commands_UpdateSymbolRefsCommand_ts["UpdateSymbolRefsCommand.ts"] --> src_storage_SymbolRegistryManager_ts["SymbolRegistryManager.ts"]
  src_commands_UpdateSymbolRefsCommand_ts["UpdateSymbolRefsCommand.ts"] --> src_doc_symbol_SymbolReferenceGenerator_ts["SymbolReferenceGenerator.ts"]
  src_commands_UpdateSymbolRefsCommand_ts["UpdateSymbolRefsCommand.ts"] --> src_types_feature_doc_symbol_ts["doc-symbol.ts"]
  src_commands_VisualizeDepsCommand_ts["VisualizeDepsCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_VisualizeDepsCommand_ts["VisualizeDepsCommand.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_VisualizeDepsCommand_ts["VisualizeDepsCommand.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_VisualizeDepsCommand_ts["VisualizeDepsCommand.ts"] --> src_visualization_MermaidGenerator_ts["MermaidGenerator.ts"]
  src_commands_VisualizeDepsCommand_ts["VisualizeDepsCommand.ts"] --> src_analyzer_DependencyChainAnalyzer_ts["DependencyChainAnalyzer.ts"]
  src_fixer_RecursiveImprover_ts["RecursiveImprover.ts"] --> src_analyzer_CodeHealthChecker_ts["CodeHealthChecker.ts"]
  src_fixer_RecursiveImprover_ts["RecursiveImprover.ts"] --> src_config_ConfigManager_ts["ConfigManager.ts"]
  src_fixer_RecursiveImprover_ts["RecursiveImprover.ts"] --> src_types_analysis_quality_ts["quality.ts"]
  src_fixer_RecursiveImprover_ts["RecursiveImprover.ts"] --> src_fixer_DocumentationFixer_ts["DocumentationFixer.ts"]
  src_fixer_RecursiveImprover_ts["RecursiveImprover.ts"] --> src_types_core_linking_ts["linking.ts"]
  src_analyzer_InterfaceAnalyzer_ts["InterfaceAnalyzer.ts"] --> src_types_tags_base_ts["base.ts"]
  src_analyzer_InterfaceAnalyzer_ts["InterfaceAnalyzer.ts"] --> src_analyzer_ASTSymbolExtractor_ts["ASTSymbolExtractor.ts"]
  src_analyzer_InterfaceAnalyzer_ts["InterfaceAnalyzer.ts"] --> src_types_domain_interface_ts["interface.ts"]
  src_analyzer_InterfaceAnalyzer_ts["InterfaceAnalyzer.ts"] --> src_types_graph_graph_ts["graph.ts"]
  src_analyzer_MissingLinkDetector_ts["MissingLinkDetector.ts"] --> src_parser_EnhancedDocExtractor_ts["EnhancedDocExtractor.ts"]
  src_analyzer_MissingLinkDetector_ts["MissingLinkDetector.ts"] --> src_types_tags_enhanced_ts["enhanced.ts"]
  src_analyzer_MissingLinkDetector_ts["MissingLinkDetector.ts"] --> src_utils_ConfigLoader_ts["ConfigLoader.ts"]
  src_analyzer_MissingLinkDetector_ts["MissingLinkDetector.ts"] --> src_types_config_config_ts["config.ts"]
  src_commands_AnalyzeCallsCommand_ts["AnalyzeCallsCommand.ts"] --> src_commands_BaseCommand_ts["BaseCommand.ts"]
  src_commands_AnalyzeCallsCommand_ts["AnalyzeCallsCommand.ts"] --> src_storage_DatabaseManager_ts["DatabaseManager.ts"]
  src_commands_AnalyzeCallsCommand_ts["AnalyzeCallsCommand.ts"] --> src_graph_SymbolGraphBuilder_ts["SymbolGraphBuilder.ts"]
  src_commands_AnalyzeCallsCommand_ts["AnalyzeCallsCommand.ts"] --> src_analyzer_CallGraphAnalyzer_ts["CallGraphAnalyzer.ts"]