graph TD
  interface_symbol["Symbol"] --> interface_contractspec["ContractSpec"]
  interface_symbol["Symbol"] --> interface_responsibilityspec["ResponsibilitySpec"]
  interface_symbol["Symbol"] --> interface_symbolrelationship["SymbolRelationship"]
  interface_symbol["Symbol"] --> interface_testmapping["TestMapping"]