/**
 * Istanbul coverage format parser
 * Works with Jest, Vitest, NYC, c8, and other tools that output Istanbul format
 *
 * @packageDocumentation
 * @responsibility Parse coverage data from coverage-final.json (Istanbul format)
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Istanbul coverage format - raw data structure
 */
interface IstanbulLocation {
  line: number;
  column: number;
}

interface IstanbulRange {
  start: IstanbulLocation;
  end: IstanbulLocation;
}

interface IstanbulFunctionData {
  name: string;
  decl?: IstanbulRange;
  loc?: IstanbulRange;
}

interface IstanbulFileData {
  path: string;
  s: Record<string, number>; // statement coverage counts
  f: Record<string, number>; // function coverage counts
  b: Record<string, number[]>; // branch coverage counts
  statementMap?: Record<string, IstanbulRange>;
  fnMap?: Record<string, IstanbulFunctionData>;
}

type IstanbulCoverageData = Record<string, IstanbulFileData>;

/**
 * Coverage data for a single file
 * @doc [[CoverageParser]]
 * @public
 */
export interface FileCoverage {
  /** File path */
  path: string;
  /** Statement coverage percentage */
  statementCoverage: number;
  /** Function coverage percentage */
  functionCoverage: number;
  /** Branch coverage percentage */
  branchCoverage: number;
  /** Line coverage percentage */
  lineCoverage: number;
  /** Covered lines */
  coveredLines: number[];
  /** Uncovered lines */
  uncoveredLines: number[];
  /** Function-level coverage */
  functions: FunctionCoverage[];
}

/**
 * Function coverage data
 * @public
 */
export interface FunctionCoverage {
  /** Function name */
  name: string;
  /** Start line */
  line: number;
  /** Whether function was called */
  covered: boolean;
  /** Call count */
  count: number;
}

/**
 * Parsed coverage summary
 * @public
 */
export interface CoverageSummary {
  /** Total files */
  totalFiles: number;
  /** Overall statement coverage */
  statements: number;
  /** Overall function coverage */
  functions: number;
  /** Overall branch coverage */
  branches: number;
  /** Overall line coverage */
  lines: number;
  /** Per-file coverage */
  files: Map<string, FileCoverage>;
}

/**
 * Istanbul coverage format parser
 *
 * @public
 * @responsibility
 * Parse Istanbul coverage format (coverage-final.json) generated by:
 * - Jest
 * - Vitest
 * - NYC
 * - c8
 * - Other Istanbul-compatible tools
 *
 * @problem Test coverage data is tool-specific and hard to integrate with documentation
 * @solves Provides universal parser for Istanbul format used by all major JS/TS test tools
 * @context Different test runners (Jest, Vitest) output different formats
 * @useCase Automatically sync test coverage into TSDoc symbol metadata
 *
 * @functionality Parse coverage JSON, Calculate coverage percentages, Extract function-level coverage
 *
 * @decision Use Istanbul format as the standard
 * @rationale Istanbul is the de-facto standard format used by Jest, Vitest, NYC, c8
 * @consequences Works with all major test tools, No custom parsers needed
 *
 * @depends fs, path
 * @depType external
 * @depReason File I/O for reading coverage-final.json
 *
 * @example
 * ```typescript
 * const parser = new CoverageParser();
 * const summary = parser.parse('coverage/coverage-final.json');
 * console.log(summary.statements); // 85.3
 * ```
 */
export class CoverageParser {
  /**
   * Parse coverage data from Istanbul format file
   *
   * @param coveragePath - Path to coverage-final.json
   * @returns Coverage summary
   *
   * @throws Error if file doesn't exist or is invalid JSON
   */
  parse(coveragePath: string): CoverageSummary {
    if (!fs.existsSync(coveragePath)) {
      throw new Error(`Coverage file not found: ${coveragePath}`);
    }

    const content = fs.readFileSync(coveragePath, 'utf-8');
    let data: IstanbulCoverageData;

    try {
      data = JSON.parse(content) as IstanbulCoverageData;
    } catch (error) {
      throw new Error(`Invalid JSON in coverage file: ${error}`);
    }

    return this.parseData(data);
  }

  /**
   * Parse raw coverage data object
   *
   * @param data - Raw Istanbul coverage data
   * @returns Coverage summary
   */
  parseData(data: IstanbulCoverageData): CoverageSummary {
    const files = new Map<string, FileCoverage>();

    let totalStatements = 0;
    let coveredStatements = 0;
    let totalFunctions = 0;
    let coveredFunctions = 0;
    let totalBranches = 0;
    let coveredBranches = 0;
    let totalLines = 0;
    let coveredLines = 0;

    for (const filePath in data) {
      const fileData = data[filePath];
      const coverage = this.parseFile(fileData);
      files.set(filePath, coverage);

      // Aggregate totals
      const sCount = Object.keys(fileData.s || {}).length;
      const sCovered = Object.values(fileData.s || {}).filter(
        (count: number) => count > 0
      ).length;

      const fCount = Object.keys(fileData.f || {}).length;
      const fCovered = Object.values(fileData.f || {}).filter(
        (count: number) => count > 0
      ).length;

      const bCount = Object.keys(fileData.b || {}).length;
      const bCovered = Object.values(fileData.b || {}).filter(
        (branches: number[]) => branches.some((b: number) => b > 0)
      ).length;

      // Line coverage
      const lineMap = this.getLineMap(fileData);
      const lCount = lineMap.size;
      const lCovered = Array.from(lineMap.values()).filter(
        covered => covered
      ).length;

      totalStatements += sCount;
      coveredStatements += sCovered;
      totalFunctions += fCount;
      coveredFunctions += fCovered;
      totalBranches += bCount;
      coveredBranches += bCovered;
      totalLines += lCount;
      coveredLines += lCovered;
    }

    return {
      totalFiles: Object.keys(data).length,
      statements: totalStatements > 0 ? (coveredStatements / totalStatements) * 100 : 0,
      functions: totalFunctions > 0 ? (coveredFunctions / totalFunctions) * 100 : 0,
      branches: totalBranches > 0 ? (coveredBranches / totalBranches) * 100 : 0,
      lines: totalLines > 0 ? (coveredLines / totalLines) * 100 : 0,
      files,
    };
  }

  /**
   * Parse coverage data for a single file
   */
  private parseFile(fileData: IstanbulFileData): FileCoverage {
    const filePath = fileData.path;

    // Statement coverage
    const sCount = Object.keys(fileData.s || {}).length;
    const sCovered = Object.values(fileData.s || {}).filter(
      (count: number) => count > 0
    ).length;
    const statementCoverage = sCount > 0 ? (sCovered / sCount) * 100 : 0;

    // Function coverage
    const fCount = Object.keys(fileData.f || {}).length;
    const fCovered = Object.values(fileData.f || {}).filter(
      (count: number) => count > 0
    ).length;
    const functionCoverage = fCount > 0 ? (fCovered / fCount) * 100 : 0;

    // Branch coverage
    const bCount = Object.keys(fileData.b || {}).length;
    const bCovered = Object.values(fileData.b || {}).filter(
      (branches: number[]) => branches.some((b: number) => b > 0)
    ).length;
    const branchCoverage = bCount > 0 ? (bCovered / bCount) * 100 : 0;

    // Line coverage
    const lineMap = this.getLineMap(fileData);
    const lineCoverage = lineMap.size > 0
      ? (Array.from(lineMap.values()).filter(c => c).length / lineMap.size) * 100
      : 0;

    const coveredLines: number[] = [];
    const uncoveredLines: number[] = [];
    for (const [line, covered] of lineMap.entries()) {
      if (covered) {
        coveredLines.push(line);
      } else {
        uncoveredLines.push(line);
      }
    }

    // Extract function coverage details
    const functions = this.extractFunctions(fileData);

    return {
      path: filePath,
      statementCoverage,
      functionCoverage,
      branchCoverage,
      lineCoverage,
      coveredLines,
      uncoveredLines,
      functions,
    };
  }

  /**
   * Build line coverage map from statement map
   */
  private getLineMap(fileData: IstanbulFileData): Map<number, boolean> {
    const lineMap = new Map<number, boolean>();
    const statementMap = fileData.statementMap || {};
    const s = fileData.s || {};

    for (const key in statementMap) {
      const location = statementMap[key];
      const covered = s[key] > 0;

      // Mark all lines in the statement range
      for (let line = location.start.line; line <= location.end.line; line++) {
        if (!lineMap.has(line) || covered) {
          lineMap.set(line, covered);
        }
      }
    }

    return lineMap;
  }

  /**
   * Extract function coverage data
   */
  private extractFunctions(fileData: IstanbulFileData): FunctionCoverage[] {
    const functions: FunctionCoverage[] = [];
    const fnMap = fileData.fnMap || {};
    const f = fileData.f || {};

    for (const key in fnMap) {
      const fn = fnMap[key];
      const count = f[key] || 0;

      functions.push({
        name: fn.name || '(anonymous)',
        line: fn.decl?.start?.line || fn.loc?.start?.line || 0,
        covered: count > 0,
        count,
      });
    }

    return functions;
  }

  /**
   * Find coverage data for specific file
   *
   * @param summary - Coverage summary
   * @param filePath - File path (can be relative or absolute)
   * @returns File coverage or null
   */
  findFile(summary: CoverageSummary, filePath: string): FileCoverage | null {
    // Try exact match first
    if (summary.files.has(filePath)) {
      return summary.files.get(filePath)!;
    }

    // Try normalized path
    const normalized = path.normalize(filePath);
    if (summary.files.has(normalized)) {
      return summary.files.get(normalized)!;
    }

    // Try basename match
    const basename = path.basename(filePath);
    for (const [key, value] of summary.files.entries()) {
      if (path.basename(key) === basename) {
        return value;
      }
    }

    // Try relative path match
    for (const [key, value] of summary.files.entries()) {
      if (key.endsWith(filePath)) {
        return value;
      }
    }

    return null;
  }

  /**
   * Get coverage for specific function in a file
   *
   * @param fileCoverage - File coverage data
   * @param functionName - Function name
   * @returns Function coverage or null
   */
  getFunctionCoverage(
    fileCoverage: FileCoverage,
    functionName: string
  ): FunctionCoverage | null {
    return fileCoverage.functions.find(f => f.name === functionName) || null;
  }
}
