#!/bin/bash

# Weekly Architecture Report
# Generates a comprehensive architecture health report
#
# Usage: ./weekly-report.sh [output-dir]

set -e

# Detect tsdoc-edge CLI
if [ -f "$(dirname "$0")/../../dist/cli.js" ]; then
  TSDOC_CMD="node $(dirname "$0")/../../dist/cli.js"
elif [ -f "$(dirname "$0")/../../src/cli.ts" ]; then
  TSDOC_CMD="npx ts-node $(dirname "$0")/../../src/cli.ts"
else
  TSDOC_CMD="tsdoc-edge"
fi

OUTPUT_DIR="${1:-./.reports}"
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
REPORT_DIR="$OUTPUT_DIR/weekly-$TIMESTAMP"

mkdir -p "$REPORT_DIR"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Generating Weekly Architecture Report"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Output: $REPORT_DIR"
echo ""

# 1. Overall Statistics
echo "📈 1. Generating overall statistics..."
$TSDOC_CMD relationship-query --stats > "$REPORT_DIR/01-statistics.txt"
echo "   ✓ Saved to 01-statistics.txt"

# 2. Critical Symbols
echo "🎯 2. Finding top 20 critical symbols..."
$TSDOC_CMD relationship-metrics --top 20 > "$REPORT_DIR/02-critical-symbols.txt"
echo "   ✓ Saved to 02-critical-symbols.txt"

# 3. Bottlenecks
echo "🚦 3. Identifying bottlenecks (betweenness)..."
$TSDOC_CMD relationship-metrics --metric betweenness --top 15 > "$REPORT_DIR/03-bottlenecks.txt"
echo "   ✓ Saved to 03-bottlenecks.txt"

# 4. Architectural Modules
echo "🏗️  4. Discovering architectural modules..."
$TSDOC_CMD relationship-clusters --min-size 5 > "$REPORT_DIR/04-modules.txt"
echo "   ✓ Saved to 04-modules.txt"

# 5. Data Quality Check
echo "✅ 5. Running data quality validation..."
$TSDOC_CMD relationship-validate > "$REPORT_DIR/05-data-quality.txt" 2>&1 || true
echo "   ✓ Saved to 05-data-quality.txt"

# 6. Export for Visualization
echo "📊 6. Exporting for visualization tools..."

echo "   • GraphML (for Gephi)..."
$TSDOC_CMD relationship-export --format graphml > "$REPORT_DIR/06-graph.graphml"
echo "     ✓ Saved to 06-graph.graphml"

echo "   • DOT (for Graphviz)..."
$TSDOC_CMD relationship-export --format dot --category structural > "$REPORT_DIR/06-structural.dot"
echo "     ✓ Saved to 06-structural.dot"

echo "   • JSON (for analysis)..."
$TSDOC_CMD relationship-export --format json > "$REPORT_DIR/06-data.json"
echo "     ✓ Saved to 06-data.json"

# 7. Generate Summary Report
echo "📝 7. Generating summary report..."

cat > "$REPORT_DIR/README.md" << EOF
# Weekly Architecture Report - $(date +%Y-%m-%d)

Generated: $(date +"%Y-%m-%d %H:%M:%S")

## Files Generated

### Analysis Reports (Text)
- \`01-statistics.txt\` - Overall relationship statistics
- \`02-critical-symbols.txt\` - Top 20 most critical symbols
- \`03-bottlenecks.txt\` - Top 15 architectural bottlenecks
- \`04-modules.txt\` - Discovered architectural modules with cohesion metrics
- \`05-data-quality.txt\` - Data integrity validation results

### Visualization Files
- \`06-graph.graphml\` - Full graph for Gephi/yEd visualization
- \`06-structural.dot\` - Structural relationships for Graphviz
- \`06-data.json\` - Complete data for custom analysis

## Quick Actions

### View in Gephi
1. Open Gephi
2. File → Open → \`06-graph.graphml\`
3. Layout → ForceAtlas 2
4. Color nodes by \`category\` attribute
5. Resize nodes by \`degree\`

### Generate Architecture Diagram
\`\`\`bash
dot -Tpng 06-structural.dot -o architecture.png
\`\`\`

### Analyze with Python
\`\`\`python
import json
with open('06-data.json') as f:
    data = json.load(f)

# data['symbols'] - All symbols
# data['relationships'] - All relationships
# data['metadata'] - Export metadata
\`\`\`

## Key Findings

$(head -30 $REPORT_DIR/02-critical-symbols.txt | tail -20)

## Data Quality

$(tail -10 $REPORT_DIR/05-data-quality.txt)

## Next Steps

1. Review critical symbols (02-critical-symbols.txt)
2. Check bottlenecks (03-bottlenecks.txt)
3. Visualize in Gephi (06-graph.graphml)
4. Compare with previous week's report

---

Generated by: \`tsdoc-edge\` Relationship Analysis System
Report Location: \`$REPORT_DIR\`
EOF

echo "   ✓ Saved to README.md"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Weekly report generated successfully!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 Report location: $REPORT_DIR"
echo ""
echo "Quick actions:"
echo "  • View summary:    cat $REPORT_DIR/README.md"
echo "  • Open in Gephi:   $REPORT_DIR/06-graph.graphml"
echo "  • Generate PNG:    dot -Tpng $REPORT_DIR/06-structural.dot -o arch.png"
echo ""
